set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR "ppc64le")

# Set the path to the cross-compiler toolchain
set(CROSS_COMPILER_PATH /usr/bin/powerpc64le-linux-gnu-)

set(CMAKE_C_COMPILER ${CROSS_COMPILER_PATH}gcc)
set(CMAKE_CXX_COMPILER ${CROSS_COMPILER_PATH}g++)
set(CMAKE_AR ${CROSS_COMPILER_PATH}ar)
set(CMAKE_ASM_COMPILER ${CROSS_COMPILER_PATH}as)
set(CMAKE_LINKER ${CROSS_COMPILER_PATH}ld)
set(CMAKE_STRIP ${CROSS_COMPILER_PATH}strip)
set(CMAKE_RANLIB ${CROSS_COMPILER_PATH}ranlib)

# Set the sysroot (if needed)
set(CMAKE_SYSROOT /)

# Set the find root path mode
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

